---
title: "Imputation"
author: "Nicolas Banholzer"
date: "2023-12-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r libraries}
library(tidyverse)
library(rstan)
library(tidybayes)
library(reshape2)
source("utils/plotting.r")
source("utils/tex.R")
```

## Data

```{r data}
# site characteristics
site_char <- readRDS("data-clean/site-characteristics.rds")

# quarterly case data
qtr_df <- readRDS("data-clean/quarterly-data.rds") %>%
  group_by(record_id) %>%
  arrange(year_quart) %>%
  mutate(time = 1:n()) %>%
  ungroup()

# annual case data
ann_df <- readRDS("data-clean/annual-data.rds")

# combine quarterly and annual case data
comb_df <- qtr_df %>%
  dplyr::select(record_id, year, quarter, year_quart, new, art, genex, tpt) %>%
  left_join(
    ann_df %>%
      dplyr::select(record_id, year, new, art, genex, tpt) %>%
      mutate(across(c(new, art, genex, tpt), ~ .x / 4)),
    by = c("record_id", "year")
  ) %>%
  mutate(
    new = ifelse(is.na(new.x), new.y, new.x),
    art = ifelse(is.na(art.x), art.y, art.x),
    tpt = ifelse(is.na(tpt.x), tpt.y, tpt.x),
    genex = ifelse(is.na(genex.x), genex.y, genex.x)
  ) %>%
  dplyr::select(-matches("[[:punct:]]x"), -matches("[[:punct:]]y")) %>%
  left_join(
    site_char %>%
      dplyr::select(record_id, matches("site_")),
    by = "record_id"
  )

# simple imputation
comb_df_imp <- comb_df %>%
  group_by(record_id) %>%
  arrange(year_quart) %>%
  fill(new, art, genex, tpt, .direction = "downup") %>%
  ungroup()
```


## Descriptives

### Site characteristics

```{r site}
char_vars <- c(
  "Region" = "site_region",
  "Clinic setting" = "site_setting",
  "Clinic owner" = "site_owner",
  "Level of care" = "site_carelevel",
  "Age of treated patients" = "site_treated",
  "Type of treated patients" = "site_patients",
  "TB-HIV service integration" = "site_integration"
)

site_char_sub <- site_char %>%
  dplyr::select(all_of(unname(char_vars))) %>%
  mutate(
    site_region = ifelse(grepl("Africa", site_region), "Africa", "Asia-Pacific"),
    site_region = factor(site_region, levels = c("Africa", "Asia-Pacific")),
  )

site_tab <- tibble(variable = character(), value = character())

for (var in char_vars) {
  if (is.factor(site_char_sub[[var]])) {
    counts <- as.numeric(table(site_char_sub[[var]]))
    perc_counts <- round(counts / sum(counts) * 100)
    val <- paste0(counts, " (", perc_counts, "%)")
    names_counts <- firstup(names(table(site_char_sub[[var]])))
    new_row <- tibble(
      variable = c(
        firstup(names(char_vars)[char_vars == var]),
        paste0("   ", names_counts)
      ),
      value = c("", val)
    )
  } else if (is.character(site_char_sub[[var]])) {
    new_row <- tibble(
      variable = c("", firstup(names(char_vars)[char_vars == var])),
      value = c("", "")
    )
  } else {
    stop(sprintf("Incorrect variable type for %s", var))
  }
  site_tab <- rbind(site_tab, new_row)
}

site_tab <- rbind(
  c("variable" = "Variable", "value" = paste0("N=", nrow(site_char))),
  site_tab
)

write.table(
  data.frame(site_tab),
  file = "results/table-site-characteristics.txt",
  row.names = FALSE, col.names = FALSE,
  sep = ",", quote = FALSE
)
```

```{r site}
char_vars_strat <- char_vars[-1]

site_tab_strat <- tibble(
  Variable = character(),
  Africa = character(),
  `Asia-Pacific` = character()
)

for (var in char_vars_strat) {
  if (is.factor(site_char_sub[[var]])) {
    counts <- matrix(table(
      site_char_sub[[var]],
      site_char_sub$site_region
    ), ncol = 2)
    perc_counts <- cbind(
      round(counts[, 1] / sum(counts[, 1]) * 100),
      round(counts[, 2] / sum(counts[, 2]) * 100)
    )
    val <- matrix(paste0(counts, " (", perc_counts, "%)"), ncol = 2)
    names_counts <- firstup(names(table(site_char_sub[[var]])))
    new_row <- tibble(
      Variable = c(
        firstup(names(char_vars)[char_vars == var]),
        paste0("   ", names_counts)
      ),
      Africa = c("", val[, 1]),
      `Asia-Pacific` = c("", val[, 2])
    )
  } else if (is.character(site_char_sub[[var]])) {
    new_row <- tibble(
      Variable = c("", firstup(names(char_vars)[char_vars == var])),
      value = c("", "")
    )
  } else {
    stop(sprintf("Incorrect variable type for %s", var))
  }
  site_tab_strat <- rbind(site_tab_strat, new_row)
}

site_tab_strat <- rbind(
  c(
    "variable" = "Variable",
    "Africa" = paste0("N=", nrow(site_char_sub[site_char_sub$site_region == "Africa", ])),
    "Asia-Pacific" = paste0("N=", nrow(site_char_sub[site_char_sub$site_region == "Asia-Pacific", ]))
  ),
  site_tab_strat
)

write.table(
  data.frame(site_tab_strat),
  file = "results/table-site-characteristics-by-region.txt",
  row.names = FALSE,
  sep = ",", quote = FALSE
)
```

### IPC measures

```{r ipc}
ipc_masks_names <- c(
  "Staff" = "Staff: any mask wearing",
  "Patients" = "Patients: any mask wearing"
)

ipc_labs <- c(
  "before",
  "since",
  "during",
  "never",
  "unknown",
  "not applicable"
)

ipc_masks <- site_char %>%
  dplyr::select(record_id, matches("_masks"), matches("ffp2")) %>%
  melt("record_id") %>%
  mutate(
    group = ifelse(grepl("staff", variable), "Staff", "Patients"),
    vlaue = ordered(value, levels = ipc_labs)
  ) %>%
  group_by(record_id, group) %>%
  summarise(
    value = min(value)
  ) %>%
  ungroup() %>%
  mutate(
    group = recode(group, !!!ipc_masks_names)
  ) %>%
  rename(variable = group)

ipc_msr_staff_names <- c(
  "msr_staff_masks" = "Face masks",
  "msr_staff_handsani" = "Hand sanitation",
  "msr_staff_glasses" = "Safety glasses",
  "msr_staff_gloves" = "Protective gloves",
  "msr_staff_clothes" = "Protective clothes"
)

ipc_msr_patient_names <- c(
  "msr_patients_masks" = "Face masks",
  "msr_patients_handsani" = "Hand sanitation",
  "msr_patients_handsoap" = "Hand hygiene"
)

ipc_msr_pat <- site_char %>%
  dplyr::select(
    record_id,
    matches("msr_patients_"),
    -matches("_masks"),
    -matches("ffp2")
  ) %>%
  left_join(
    ipc_masks %>%
      filter(variable == "Patients: any mask wearing") %>%
      rename(msr_patients_masks = value) %>%
      dplyr::select(-variable)
  ) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!ipc_msr_patient_names),
    variable = factor(variable, levels = ipc_msr_patient_names)
  )

ipc_msr_staff <- site_char %>%
  dplyr::select(
    record_id,
    matches("msr_staff"),
    -matches("_masks"),
    -matches("ffp2")
  ) %>%
  left_join(
    ipc_masks %>%
      filter(variable == "Staff: any mask wearing") %>%
      rename(msr_staff_masks = value) %>%
      dplyr::select(-variable)
  ) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!ipc_msr_staff_names),
    variable = factor(variable, levels = rev(ipc_msr_staff_names))
  )

ipc_dist_names <- c(
  "distance_phys" = "Physical distancing",
  "distance_triage" = "Patient triage",
  "distance_wr_sep" = "Separate waiting rooms",
  "distance_wr_open" = "Outside waiting room",
  "distance_fixed_app" = "Fixed appointments",
  "distance_comm_area" = "Closure of some common areas",
  "distance_patients" = "Restricted number of patients",
  "distance_visitors" = "Restricted number of visitors"
)

ipc_dist <- site_char %>%
  dplyr::select(record_id, matches("distance_")) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!ipc_dist_names),
    variable = factor(variable, levels = rev(ipc_dist_names))
  )

ipc_env_names <- c(
  "envmt_surf_cln" = "Surface cleaning",
  "envmt_vent" = "Natural ventilation"
)

ipc_env <- site_char %>%
  dplyr::select(record_id, matches("envmt_")) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!ipc_env_names),
    variable = factor(variable, levels = rev(ipc_env_names))
  )
```

### Drug shortages

```{r shortages}
drug_short <- site_char %>%
  dplyr::select(matches("drugs_")) %>%
  mutate_all(~ ifelse(.x == "yes", 1,
    ifelse(.x == "not applicable", NA, 0)
  )) %>%
  mutate(
    short_drug = rowSums(., na.rm = TRUE),
    short_drug = ifelse(is.na(short_drug), "not applicable",
      ifelse(short_drug > 0, "yes", "no")
    )
  ) %>%
  mutate(variable = "Drug shortages") %>%
  rename(value = short_drug) %>%
  bind_cols(record_id = site_char$record_id) %>%
  dplyr::select(record_id, variable, value)
```

### Care changes

```{r care}
care_names <- c(
  "changes_hrs" = "Reduced opening hours",
  "changes_clos" = "Temporary closure",
  "changes_staff" = "Staff shortages",
  "changes_res" = "Equipment shortages",
  "changes_lab" = "Reduced laboratory services"
)

care_changes <- site_char %>%
  dplyr::select(all_of(c("record_id", names(care_names)))) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!care_names),
    variable = factor(variable, levels = rev(care_names))
  )

care_dot_names <- c(
  "changes_dot_comm" = "F2F DOT with community memember",
  "changes_dot_fam" = "F2F DOT with family member",
  "changes_dot_virt_cl" = "Virtual DOT with staff member",
  "changes_dot_virt_comm" = "Virtual DOT with community member"
)

care_dot_changes <- site_char %>%
  dplyr::select(record_id, matches("changes_dot")) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!care_dot_names),
    variable = factor(variable, levels = rev(care_dot_names))
  )
```

### Restrictions

```{r restrictions}
restr_names <- c(
  "restr_tb_diag" = "Reduced access to diagnostics",
  "restr_tb_tr" = "Delayed treatment initiation",
  "restr_tb_tpt" = "Delayed preventive therapy",
  "restr_tb_ct" = "Restricted contact tracing",
  "restr_tb_dot" = "Restricted directly observed therapy"
)

restr <- site_char %>%
  dplyr::select(record_id, matches("restr_"), -matches("tb_restr")) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!restr_names),
    variable = factor(variable, levels = rev(restr_names))
  )

restr_addr_names <- c(
  "tb_restr_addr_tele" = "Telehealth services",
  "tb_restr_addr_diff" = "Differentiated service delivery",
  "tb_restr_addr_drugs" = "Prolonged drug dispension",
  "tb_restr_addr_dot" = "Changes in directly observed therapy provision"
)

restr_addr <- site_char %>%
  dplyr::select(record_id, matches("tb_restr_addr_")) %>%
  melt("record_id") %>%
  mutate(
    variable = recode(variable, !!!restr_addr_names),
    variable = factor(variable, levels = rev(restr_addr_names))
  )
```

### Summaries 

```{r summaries}
ipc_dist %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "during")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_dist %>%
  group_by(record_id) %>%
  summarize(a = any(value == "before")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_dist %>%
  group_by(record_id) %>%
  summarize(a = !any(value == "since" | value == "during" | value == "before")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_dist %>%
  group_by(variable) %>%
  summarize(
    n = sum(value == "since"),
    p = round(100 * n / n_distinct(ipc_dist$record_id))
  ) %>%
  ungroup()

ipc_env %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "during")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_env %>%
  group_by(record_id) %>%
  summarize(a = all(value == "before")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_msr_staff %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "during")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_msr_staff %>%
  filter(variable == "Face masks" | variable == "Hand sanitation") %>%
  group_by(variable) %>%
  summarize(
    n = sum(value == "since" | value == "during"),
    p = round(100 * n / n_distinct(ipc_msr_staff$record_id))
  ) %>%
  ungroup()

ipc_msr_pat %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "during")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

ipc_msr_pat %>%
  filter(variable == "Face masks" | variable == "Hand sanitation") %>%
  group_by(variable) %>%
  summarize(
    n = sum(value == "since" | value == "during"),
    p = round(100 * n / n_distinct(ipc_msr_staff$record_id))
  ) %>%
  ungroup()

rbind(
  ipc_dist, ipc_env, ipc_msr_staff, ipc_msr_pat
) %>%
  group_by(record_id) %>%
  summarize(n = sum(value == "since")) %>%
  ungroup() %>%
  summarize(
    mean = mean(n)
  )

rbind(
  ipc_dist, ipc_env, ipc_msr_staff, ipc_msr_pat
) %>%
  group_by(record_id) %>%
  summarize(n = sum(value == "before")) %>%
  ungroup() %>%
  summarize(
    mean = mean(n)
  )

rbind(
  ipc_dist, ipc_env, ipc_msr_staff, ipc_msr_pat
) %>%
  summarise(n_distinct(variable))

care_changes %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "during")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

care_changes %>%
  group_by(record_id) %>%
  summarize(a = any(value == "since" | value == "after")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

restr %>%
  group_by(record_id) %>%
  summarize(a = any(value == "yes")) %>%
  ungroup() %>%
  summarize(
    n = n(),
    n_since = sum(a),
    p = n_since / n
  )

restr_addr %>%
  mutate(value = ifelse(value == "since", "during", value)) %>%
  group_by(variable, value) %>%
  summarize(
    n = n(),
    p = round(100 * n() / n_distinct(restr_addr$record_id))
  ) %>%
  ungroup() %>%
  arrange(value)

restr_addr %>%
  group_by(variable, value) %>%
  summarize(
    n = n(),
    p = round(100 * n() / n_distinct(restr_addr$record_id))
  ) %>%
  ungroup() %>%
  arrange(value)
```

### Plot

```{r plot}
types <- c(
  "A | Have you implemented distancing and separation measures?",
  "B | Have you implemented environmental protective measures?",
  "C | Have you implemented personal protective measures for staff?",
  "D | Have you implemented personal protective measures for patients?",
  "E | Have you observed changes in services during the pandemic?",
  "F | Have you observed drug shortages during the pandemic?",
  "G | Have you experienced restrictions in TB services during the pandemic?",
  "H | How did you address disruptions in TB services?",
  "I | How did you change DOT provisions to address disruptions in TB services?"
)

val_labs <- c(
  "before" = "Yes | Already in place before the pandemic",
  "since" = "Yes | Introduced during pandemic and maintained since then",
  "after" = "Yes | Introduced during pandemic and maintained since then",
  "during" = "Yes | Only in place during pandemic",
  "yes" = "Yes | Only in place during pandemic",
  "no" = "No | Never in place | Not observed",
  "never" = "No | Never in place | Not observed",
  "unknown" = "Information not available",
  "not applicable" = "Not applicable"
)

site_surv <- rbind(
  ipc_dist %>% mutate(type = types[1]),
  ipc_env %>% mutate(type = types[2]),
  ipc_msr_staff %>% mutate(type = types[3]),
  ipc_msr_pat %>% mutate(type = types[4]),
  care_changes %>% mutate(type = types[5]),
  drug_short %>% mutate(type = types[6]),
  restr %>% mutate(type = types[7]),
  restr_addr %>% mutate(type = types[8])
  # care_dot_changes %>% mutate(type = types[9])
) %>%
  mutate(
    value = recode(value, !!!val_labs),
    value = factor(value, levels = rev(unique(val_labs))),
    type = factor(type, levels = types),
    variable = factor(variable, levels = c(
      rev(ipc_dist_names), rev(ipc_env_names),
      "Hand hygiene", rev(ipc_msr_staff_names),
      rev(care_names), "Drug shortages",
      rev(restr_names), rev(restr_addr_names)
    ))
  ) %>%
  group_by(type, variable, value) %>%
  summarize(n = n()) %>%
  ungroup()

cols <- c(
  wes_palette("Chevalier1")[1],
  wes_palette("Darjeeling2")[2],
  # wes_palette("Zissou1")[1],
  wes_palette("Darjeeling2")[4],
  wes_palette("Zissou1")[4],
  "grey40",
  "grey80"
)

site_surv_pl <- site_surv %>%
  ggplot(aes(y = variable, x = n, fill = value)) +
  ggforce::facet_col(type ~ ., scales = "free_y", space = "free") +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(
    aes(label = n),
    position = position_stack(vjust = .5),
    size = 8 / cm(1),
    color = "white"
  ) +
  labs(x = "Number of sites") +
  scale_fill_manual(values = rev(cols)) +
  coord_cartesian(expand = FALSE) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical",
    legend.justification = "left",
    legend.key.width = unit(.15, "cm"),
    legend.key.height = unit(.3, "cm"),
    legend.title = element_blank(),
    axis.title.x = element_text(size = 8, margin = margin(t = 5.5)),
    axis.text.y = element_text(size = 8, hjust = 1, margin = margin(r = 5)),
    strip.text = element_text(
      size = 8,
      face = 2,
      margin = margin(b = 5.5),
      hjust = 0
    ),
    panel.spacing = unit(0.5, "cm")
  ) +
  guides(fill = guide_legend(ncol = 1, reverse = TRUE, byrow = TRUE))

save_plot(
  site_surv_pl,
  pdf_file = "results/survey.png",
  w = 16,
  h = 23
)
```


### Association IPC and site char

```{r assoc}
site_char_main <- site_char %>%
  mutate(
    site_region = ifelse(
      grepl("Africa", site_region),
      "Africa", "Asia-Pacific"
    ),
    site_region = factor(site_region, levels = c("Africa", "Asia-Pacific")),
    site_carelevel = factor(
      ifelse(site_carelevel == "tertiary", "Tertiary", "Secondary/Primary"),
      levels = c("Secondary/Primary", "Tertiary")
    ),
    site_integration = factor(
      ifelse(site_integration == "full", "Full", "Partial"),
      levels = c("Partial", "Full")
    ),
    site_treated = factor(
      ifelse(site_treated == "only adults", "Adults only", "Adults & children"),
      levels = c("Adults only", "Adults & children")
    )
  ) %>%
  dplyr::select(
    record_id,
    site_region,
    site_carelevel,
    site_integration,
    site_treated
  )

main_char_names <- c(
  "site_region" = "Region",
  "site_carelevel" = "Level of care",
  "site_integration" = "TB-HIV service integration",
  "site_treated" = "Age of treated patients"
)

ipc <- rbind(
  ipc_dist %>% mutate(type = "Distancing measures"),
  ipc_env %>% mutate(type = "Environmental measures"),
  ipc_msr_staff %>% mutate(type = "Staff protective measures"),
  ipc_msr_pat %>% mutate(type = "Patient protective measures")
) %>%
  left_join(site_char_main, by = "record_id") %>%
  mutate(
    value = recode(value, !!!val_labs)
  ) %>%
  filter(!(value %in% c("Information not available", "Not applicable"))) %>%
  rename(ipc = variable) %>%
  melt(c("record_id", "type", "ipc", "value"), value.name = "char") %>%
  mutate(
    variable = recode(variable, !!!main_char_names),
    value = factor(value, levels = rev(rev(unique(val_labs))[-c(1:2)]))
  )

ipc %>%
  filter(variable == "Region") %>%
  group_by(record_id, value) %>%
  summarize(n_ipc = n()) %>%
  ungroup() %>%
  group_by(value) %>%
  summarise(sum_n_ipc = sum(n_ipc)) %>%
  ungroup() %>%
  mutate(p_ipc = round(100 * sum_n_ipc / sum(sum_n_ipc)))

ipc_sum <- ipc %>%
  group_by(record_id, variable, char, value) %>%
  summarize(n_ipc = n()) %>%
  ungroup() %>%
  group_by(variable, char, value) %>%
  summarise(sum_n_ipc = sum(n_ipc)) %>%
  ungroup() %>%
  group_by(variable, char) %>%
  mutate(p_ipc = sum_n_ipc / sum(sum_n_ipc)) %>%
  ungroup() %>%
  group_by(variable, char) %>%
  complete(
    value,
    fill = list(sum_n_ipc = 0, p_ipc = 0)
  )

ipc_pval <- tibble(variable = character(), pval = double())
for (v in unique(ipc$variable)) {
  ipc_sub <- ipc %>%
    filter(variable == v)
  cont_tbl <- table(ipc_sub$value, ipc_sub$char)
  test <- chisq.test(cont_tbl)$p.value
  ipc_pval <- rbind(ipc_pval, tibble(variable = v, pval = test))
}

ipc_pval$pval_txt <- ifelse(ipc_pval$pval < 0.001, "p<0.001",
  ifelse(ipc_pval$pval < 0.01, paste0("p=", round(ipc_pval$pval, 3)),
    paste0("p=", round(ipc_pval$pval, 2))
  )
)

ipc_sum_list <- ipc_sum %>%
  split(.$variable)

ipc_assoc_pl_list <- lapply(ipc_sum_list, function(dat) {
  dat %>%
    ggplot(aes(x = char, fill = value, group = value, y = p_ipc)) +
    geom_col(
      width = .8,
      position = position_dodge2(width = .8, preserve = "single")
    ) +
    geom_text(
      aes(label = paste0(round(100 * p_ipc), "%")),
      position = position_dodge2(width = .8, preserve = "single"),
      vjust = -.5,
      size = 7 / cm(1),
      color = "black",
      inherit.aes = TRUE
    ) +
    ggsignif::geom_signif(
      y_position = .55,
      xmin = 1,
      xmax = 2,
      annotation = ipc_pval$pval_txt[ipc_pval$variable == dat$variable[1]],
      tip_length = 0.03,
      step_increase = 0.2,
      textsize = 8 / cm(1),
      vjust = -.5
    ) +
    scale_fill_manual(values = cols[-c(5:6)]) +
    scale_y_continuous(
      limits = c(0, 0.55),
      breaks = seq(0, 0.55, 0.1),
      expand = expansion(mult = c(0, 0.1)),
      labels = function(x) x * 100
    ) +
    labs(
      title = dat$variable[1],
      y = "Total proportion of IPC measures (%)"
    ) +
    theme_custom() +
    theme(
      legend.position = "bottom",
      legend.direction = "vertical",
      legend.justification = "left",
      legend.key.width = unit(.15, "cm"),
      legend.key.height = unit(.3, "cm"),
      legend.title = element_blank(),
      axis.title.x = element_blank(),
      plot.title.position = "plot",
      plot.title = element_text(hjust = 0.5)
    )
})

ipc_assoc_pl <- ipc_assoc_pl_list[[1]] + ipc_assoc_pl_list[[2]] + ipc_assoc_pl_list[[3]] + ipc_assoc_pl_list[[4]] + plot_layout(guides = "collect", ncol = 2, axis_titles = "collect")

# Add the legend
ipc_assoc_pl <- ipc_assoc_pl & theme(legend.position = "bottom")

save_plot(
  ipc_assoc_pl,
  pdf_file = "results/ipc-association.png",
  w = 16,
  h = 14
)
```

### Case outcomes

```{r global}
comb_df_imp %>%
  group_by(year_quart) %>%
  summarize(
    new = sum(new, na.rm = TRUE),
    art = sum(art, na.rm = TRUE),
    genex = sum(genex, na.rm = TRUE),
    tpt = sum(tpt, na.rm = TRUE)
  ) %>%
  melt("year_quart") %>%
  ggplot(aes(x = year_quart, y = value)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y") +
  coord_cartesian(expand = FALSE) +
  theme_custom()
```

```{r region}
comb_df_imp %>%
  group_by(year, site_region) %>%
  summarize(
    new = sum(new, na.rm = TRUE),
    art = sum(art, na.rm = TRUE),
    genex = sum(genex, na.rm = TRUE),
    tpt = sum(tpt, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  group_by(site_region) %>%
  arrange(year) %>%
  mutate(across(c(new, art, genex, tpt), ~ 100 * .x / .x[1])) %>%
  ungroup() %>%
  melt(c("year", "site_region")) %>%
  ggplot(aes(x = year, y = value, color = site_region)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y") +
  coord_cartesian(expand = FALSE) +
  theme_custom()
```

```{r within-region}
comb_df_imp %>%
  group_by(year, site_region, record_id) %>%
  summarize(
    new = sum(new, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  group_by(record_id, site_region) %>%
  arrange(year) %>%
  mutate(new = 100 * new / new[1]) %>%
  ungroup() %>%
  ggplot(aes(x = year, y = new, color = factor(record_id))) +
  geom_line() +
  facet_wrap(~site_region, scales = "free_y") +
  coord_cartesian(expand = FALSE) +
  theme_custom()
```

```{r within-country}
comb_df_imp %>%
  group_by(year, site_country, record_id) %>%
  summarize(
    new = sum(new, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  group_by(record_id, site_country) %>%
  arrange(year) %>%
  mutate(new = 100 * new / new[1]) %>%
  ungroup() %>%
  ggplot(aes(x = year, y = new, color = factor(record_id))) +
  geom_line() +
  facet_wrap(~site_country, scales = "free_y") +
  coord_cartesian(expand = FALSE) +
  theme_custom()
```

```{r within-site-char}
# overall correlation
new_df <- comb_df_imp %>%
  group_by(record_id) %>%
  mutate(all_na = all(is.na(new))) %>%
  ungroup() %>%
  filter(!all_na)

site_cor <- new_df %>%
  dplyr::select(record_id, year_quart, new) %>%
  dcast(year_quart ~ record_id) %>%
  dplyr::select(-year_quart) %>%
  as.matrix()

overall_cor <- cor(site_cor, method = "spearman")
overall_cor <- round(mean(overall_cor[lower.tri(overall_cor)]), 2)

cor_by_group <- function(variable) {
  cat <- as.character(unique(new_df[[variable]]))

  cat_cor <- c()
  for (i in 1:length(cat)) {
    cor_mat <- new_df %>%
      filter(!!sym(variable) == cat[i]) %>%
      dplyr::select(record_id, year_quart, new) %>%
      dcast(year_quart ~ record_id) %>%
      dplyr::select(-year_quart) %>%
      as.matrix() %>%
      cor(method = "spearman")

    correl <- cor_mat[lower.tri(cor_mat)]

    cat_cor[i] <- round(mean(correl), 2)
  }

  paste0(
    paste0(c("Overall", cat), ": "),
    c(overall_cor, cat_cor),
    collapse = "     "
  )
}

cor_by_group("site_region")
cor_by_group("site_country")
cor_by_group("site_setting")
cor_by_group("site_treated")
cor_by_group("site_patients")
cor_by_group("site_integration")
cor_by_group("site_carelevel")
cor_by_group("site_owner")
```

### Granger causality

```{r granger}
library(plm)
library(car)

cases_art <- pdata.frame(
  qtr_df %>%
    group_by(record_id) %>%
    filter(all(!is.na(new)) & all(!is.na(art))) %>%
    arrange(year_quart) %>%
    mutate(time = 1:n()) %>%
    mutate(
      new = log1p(new),
      art = log1p(art),
      genex = log1p(genex),
    ) %>%
    ungroup() %>%
    dplyr::select(record_id, time, year, quarter, new, art),
  index = c("record_id", "time")
)

n_distinct(cases_art$record_id)

pgrangertest(new ~ art, data = cases_art, order = 4L)
pgrangertest(art ~ new, data = cases_art, order = 4L)

pgrangertest(new ~ art, data = cases_art, order = 2L)
pgrangertest(art ~ new, data = cases_art, order = 2L)

plm_lag_art <- plm(
  new ~ lag(new, 1:4) + lag(art, 1:4) + factor(quarter) + factor(year),
  data = cases_art,
  model = "fd"
)

summary(plm_lag_art)

xnames <- names(coef(plm_lag_art))
xnames <- xnames[grepl("art,", xnames)]
linearHypothesis(plm_lag_art, xnames)

plm_lag_new <- plm(
  art ~ lag(new, 1:4) + lag(art, 1:4) + factor(quarter) + factor(year),
  data = cases_art,
  model = "fd"
)

summary(plm_lag_new)

xnames2 <- names(coef(plm_lag_new))
xnames2 <- xnames2[grepl("new,", xnames2)]
linearHypothesis(plm_lag_new, xnames2)


plm_cor <- plm(
  new ~ genex + factor(quarter) + factor(year),
  data = cases_art,
  model = "fd"
)

summary(plm_cor)
```


## Imputation

### Prepare data

```{r prep}
prep_data <- function(outcome, exclude_ids = NULL) {
  if (!is.null(exclude_ids)) {
    comb_df_filt <- comb_df %>%
      filter(!(record_id %in% exclude_ids))
  } else {
    comb_df_filt <- comb_df
  }

  qadf <- comb_df_filt %>%
    group_by(record_id) %>%
    arrange(year, quarter) %>%
    mutate(
      time = 1:n(),
      all_na = all(is.na(!!sym(outcome)))
    ) %>%
    ungroup() %>%
    filter(!all_na) %>%
    arrange(record_id, time) %>%
    mutate(ind = 1:n()) %>%
    rename(y = !!sym(outcome))

  qadf <- qadf %>%
    left_join(
      qtr_df %>%
        dplyr::select(record_id, year, quarter, !!sym(outcome)),
      by = c("record_id", "year", "quarter")
    ) %>%
    left_join(
      ann_df %>%
        dplyr::select(record_id, year, !!sym(outcome)),
      by = c("record_id", "year")
    ) %>%
    mutate(
      across(
        c(site_region, site_country, time, year, quarter),
        ~ as.integer(factor(.x)),
        .names = "{.col}_ind"
      ),
      year_ind = year - min(year) + 1,
      record_id_int = as.integer(factor(record_id))
    )


  # create stan data frame
  sdf <- list()

  # indices
  sdf$N <- nrow(qadf)
  sdf$N_times <- n_distinct(qadf$time)
  sdf$N_years <- n_distinct(qadf$year)
  sdf$N_sites <- n_distinct(qadf$record_id)
  sdf$N_countries <- n_distinct(qadf$site_country)
  sdf$N_regions <- n_distinct(qadf$site_region)

  # groups
  sdf$time_ind <- qadf$time_ind
  sdf$year_ind <- qadf$year_ind
  sdf$quarter_ind <- qadf$quarter
  sdf$site_ind <- qadf$record_id_int
  sdf$region_ind <- qadf$site_region_ind
  sdf$country_ind <- qadf$site_country_ind
  sdf$site_region_ind <- qadf %>%
    group_by(record_id_int) %>%
    slice(1) %>%
    ungroup() %>%
    arrange(record_id_int) %>%
    dplyr::select(site_region_ind) %>%
    unlist()
  sdf$site_country_ind <- qadf %>%
    group_by(record_id_int) %>%
    slice(1) %>%
    ungroup() %>%
    arrange(record_id_int) %>%
    dplyr::select(site_country_ind) %>%
    unlist()

  # time
  sdf$time_year_ind <- qadf %>%
    group_by(time_ind) %>%
    slice(1) %>%
    ungroup() %>%
    arrange(time_ind) %>%
    dplyr::select(year_ind) %>%
    unlist()
  sdf$time_quart_ind <- qadf %>%
    group_by(time_ind) %>%
    slice(1) %>%
    ungroup() %>%
    arrange(time_ind) %>%
    dplyr::select(quarter_ind) %>%
    unlist()

  # outcome
  sdf$y <- qadf[["y"]]
  sdf$y <- ifelse(is.na(sdf$y), -1, sdf$y)
  sdf$missing <- ifelse(!is.na(qadf[[paste0(outcome, ".x")]]), 0,
    ifelse(is.na(qadf[[paste0(outcome, ".y")]]), -1, 1)
  )
  sdf$K_missing <- sum(sdf$missing < 0)
  sdf$J_missing_quart <- sum(sdf$missing > 0)
  sdf$missing_ind <- numeric(sdf$N)
  sdf$missing_quart_group_ind <- numeric(sdf$N)
  k <- 0
  j <- 0
  j_g <- 1
  for (n in 1:sdf$N) {
    if (sdf$missing[n] < 0) {
      k <- k + 1
      sdf$missing_ind[n] <- k
    }
    if (sdf$missing[n] > 0) {
      j <- j + 1
      sdf$missing_ind[n] <- j
      sdf$missing_quart_group_ind[n] <- j_g
      j_g <- j_g + ifelse(j %% 4 == 0, 1, 0)
    }
  }
  sdf$J_missing_years <- max(sdf$missing_quart_group_ind)
  sdf$y_annual <- c()
  for (j in 1:sdf$J_missing_years) {
    sdf$y_annual[j] <- sum(sdf$y[sdf$missing_quart_group_ind == j])
  }

  return(list(dat = qadf, stan_dat = sdf))
}
```

### Model setup

```{r}
seed <- 12345
model_file <- "models/imputation-hierarchical-gp.stan"
nc <- 4
chains <- 4
iterations <- 2000
```

```{r}
get_estimates <- function(dat, stan_dat, mod) {
  # observed data
  df_obs <- dat %>%
    dplyr::select(
      "ind",
      "record_id",
      "record_id_int",
      "year",
      "year_quart",
      "site_region",
      "site_country",
      "site_carelevel",
      "site_integration",
      "y"
    )

  # empty forecast data
  df_fcat <- expand.grid(
    record_id_int = sort(unique(stan_dat$site_ind)),
    year_quart = max(df_obs$year) + 1 + c(.25, .50, .75, 1)
  ) %>%
    arrange(record_id_int) %>%
    mutate(
      year = floor(year_quart),
      ind = max(df_obs$ind) + 1:n()
    ) %>%
    left_join(
      df_obs %>%
        dplyr::select(record_id, record_id_int) %>%
        distinct(),
      by = "record_id_int"
    )

  # combine
  df_obs <- rbind(
    dplyr::select(df_obs, record_id, record_id_int, year, year_quart, ind),
    df_fcat
  ) %>%
    left_join(df_obs, by = c("ind", "record_id", "record_id_int", "year", "year_quart")) %>%
    group_by(record_id) %>%
    fill(
      site_region, site_country,
      site_carelevel, site_integration,
      .direction = "downup"
    ) %>%
    mutate(
      site_carelevel = factor(
        ifelse(site_carelevel == "tertiary", "Tertiary", "Primary/Secondary"),
        levels = c("Primary/Secondary", "Tertiary")
      ),
      site_integration = factor(
        ifelse(site_integration == "full", "Fully integrated", "Not integrated"),
        levels = c("Not integrated", "Fully integrated")
      ),
      site_region = factor(
        ifelse(site_region == "Asia-Pacific", "Asia-Pacific", "Africa"),
        levels = c("Asia-Pacific", "Africa")
      )
    )

  # get predictions
  df_pred <- spread_draws(mod, y_pred[ind]) %>%
    rename(pred = y_pred) %>%
    left_join(df_obs, by = c("ind")) %>%
    mutate(
      year_quart = ifelse(is.na(year_quart), year, year_quart),
      record_id = paste0(record_id, ": ", site_country, " (", site_region, ")")
    )

  return(df_pred)
}
```

### Models

#### New

```{r model}
df_new <- prep_data("new")

m_new <- stan(
  file = model_file,
  chains = chains,
  iter = iterations,
  cores = nc,
  seed = seed,
  data = df_new$stan_dat
)
```

```{r check}
summary(
  m_new,
  pars = c(
    "tot_var", "prop_var",
    "sigma_region", "sigma_country",
    "length_GP_site_short", "length_GP_site_long",
    "length_GP_region_short", "length_GP_region_long",
    "sigma_GP_site_short", "sigma_GP_site_long",
    "sigma_GP_region_short",
    "sigma_GP_region_long",
    "alpha"
  )
)$summary %>%
  round(3)

m_new %>%
  spread_draws(site_re[k]) %>%
  ggplot(aes(y = factor(k), x = site_re)) +
  stat_pointinterval() +
  geom_vline(aes(xintercept = 0), linetype = "dashed")

m_new %>%
  spread_draws(country_re[site_country_ind]) %>%
  left_join(df_new$dat %>% dplyr::select(site_country_ind, site_country)) %>%
  ggplot(aes(y = site_country, x = country_re)) +
  stat_pointinterval() +
  geom_vline(aes(xintercept = 0), linetype = "dashed")

m_new %>%
  spread_draws(region_re[site_region_ind]) %>%
  left_join(df_new$dat %>% dplyr::select(site_region_ind, site_region)) %>%
  ggplot(aes(y = site_region, x = region_re)) +
  stat_pointinterval() +
  geom_vline(aes(xintercept = 0), linetype = "dashed")

m_new %>%
  spread_draws(
    sigma_GP_site_short, sigma_GP_region_short,
    sigma_GP_site_long, sigma_GP_region_long
  ) %>%
  dplyr::select(
    sigma_GP_site_short, sigma_GP_region_short,
    sigma_GP_site_long, sigma_GP_region_long
  ) %>%
  gather() %>%
  ggplot(aes(y = key, x = value)) +
  stat_pointinterval() +
  geom_vline(aes(xintercept = 0), linetype = "dashed")
```

```{r fit}
# get estimates/predictions
pred_new <- get_estimates(df_new$dat, df_new$stan_dat, m_new)

# plot model fit
ggplot(mapping = aes(x = year_quart)) +
  stat_lineribbon(
    data = pred_new,
    mapping = aes(y = pred),
    .width = c(.5, .95)
  ) +
  geom_line(
    data = pred_new %>% group_by(record_id, year_quart) %>% slice(1),
    mapping = aes(y = y),
    color = "red"
  ) +
  facet_wrap(~record_id, scales = "free_y") +
  scale_fill_brewer()
```

#### ART

```{r model}
df_art <- prep_data("art")

m_art <- stan(
  file = model_file,
  chains = chains,
  iter = iterations,
  cores = nc,
  seed = seed,
  data = df_art$stan_dat
)
```

```{r fit}
# get estimates/predictions
pred_art <- get_estimates(df_art$dat, df_art$stan_dat, m_art)

# plot model fit
ggplot(mapping = aes(x = year_quart)) +
  stat_lineribbon(
    data = pred_art %>% filter(year_quart <= 2023),
    mapping = aes(y = pred),
    .width = c(.5, .95)
  ) +
  geom_line(
    data = pred_art %>% group_by(record_id, year_quart) %>% slice(1) %>% filter(year_quart <= 2023),
    mapping = aes(y = y),
    color = "red"
  ) +
  facet_wrap(~record_id, scales = "free_y") +
  scale_fill_brewer()

ggsave("results/art-by-site.png", width = 16, height = 12)
```

#### Genex

```{r model}
df_genex <- prep_data("genex")

m_genex <- stan(
  file = model_file,
  chains = chains,
  iter = iterations,
  cores = nc,
  seed = seed,
  data = df_genex$stan_dat
)
```

```{r fit}
# get estimates/predictions
pred_genex <- get_estimates(df_genex$dat, df_genex$stan_dat, m_genex)

# plot model fit
ggplot(mapping = aes(x = year_quart)) +
  stat_lineribbon(
    data = pred_genex,
    mapping = aes(y = pred),
    .width = c(.5, .95)
  ) +
  geom_line(
    data = pred_genex %>% group_by(record_id, year_quart) %>% slice(1),
    mapping = aes(y = y),
    color = "red"
  ) +
  facet_wrap(~record_id, scales = "free_y") +
  scale_fill_brewer()
```

### Plot imputed outcomes

```{r plot}
pred_df <- bind_rows(
  pred_new %>%
    mutate(outcome = "Newly diagnosed TB cases") %>%
    mutate(subgroup = "Global"),
  pred_new %>%
    mutate(outcome = "Newly diagnosed TB cases") %>%
    mutate(subgroup = site_region),
  # pred_new %>%
  #   mutate(outcome = "Newly diagnosed TB cases") %>%
  #   mutate(subgroup = site_integration),
  pred_art %>%
    mutate(outcome = "New patients on ART") %>%
    mutate(subgroup = "Global"),
  pred_art %>%
    mutate(outcome = "New patients on ART") %>%
    mutate(subgroup = site_region),
  # pred_art %>%
  #   mutate(outcome = "New patients on ART") %>%
  #   mutate(subgroup = site_integration),
  pred_genex %>%
    mutate(outcome = "Number of GeneXpert done") %>%
    mutate(subgroup = "Global"),
  pred_genex %>%
    mutate(outcome = "Number of GeneXpert done") %>%
    mutate(subgroup = site_region),
  # pred_genex %>%
  #   mutate(outcome = "Number of GeneXpert done") %>%
  #   mutate(subgroup = site_integration)
)

subgroup_lab <- c(
  "Global" = "Global",
  "Africa" = "Africa",
  "Asia-Pacific" = "Asia Pacific"
)

est_cases <- pred_df %>%
  group_by(.draw, year_quart, outcome, subgroup) %>%
  summarize(pred = sum(pred)) %>%
  ungroup() %>%
  group_by(year_quart, outcome, subgroup) %>%
  median_qi() %>%
  ungroup() %>%
  filter(year_quart <= 2023) %>%
  # mutate(
  #   forecast = ifelse(year_quart > 2023.25, "Forecast", "Observed"),
  #   forecast = factor(forecast, levels = c("Forecast", "Observed"))
  # ) %>%
  # group_by(outcome, subgroup) %>%
  # mutate(type = data.table::rleid(forecast)) %>%
  # ungroup() %>%
  mutate(
    outcome = dplyr::recode(outcome, !!!outcome_lab),
    subgroup = dplyr::recode(subgroup, !!!subgroup_lab),
    outcome = factor(outcome, levels = outcome_lab),
    subgroup = factor(subgroup, levels = subgroup_lab)
  )

# est_cases <- rbind(
#   est_cases,
#   est_cases[est_cases$year_quart == 2023.25, ] %>%
#     mutate(type = 2, forecast = "Forecast")
# )

pl <- ggplot(
  data = est_cases,
  mapping = aes(x = year_quart) #  - .25
) +
  geom_line(aes(y = pred)) + # , color = forecast, group = type
  geom_ribbon(
    aes(
      ymin = .lower, ymax = .upper
      # fill = forecast, group = type
    ),
    alpha = .25
  ) +
  facet_wrap(
    outcome ~ subgroup,
    dir = "v",
    ncol = 3,
    scales = "free"
  ) +
  scale_color_manual(values = c("darkred", "black")) +
  scale_fill_manual(values = c("darkred", "black")) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0)),
    limits = c(2018.25, 2023.25),
    breaks = seq(2018.25, 2023.25, 1),
    labels = function(x) x - 0.25
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    labels = scales::comma
  ) +
  labs(
    fill = "CrI"
  ) +
  theme_custom() +
  theme(
    legend.position = "none",
    axis.title = element_blank(),
    panel.spacing = unit(.5, "cm"),
    strip.text = element_text(size = 8, face = 2, margin = margin(b = 5.5)),
    plot.margin = margin(r = 10),
  )

save_plot(
  pl,
  pdf_file = "results/imputed-outcomes.png",
  w = 16, h = 14
)
```

#### TPT

```{r tpt-model}
df_tpt <- prep_data("tpt", exclude_ids = 45)

m_tpt <- stan(
  file = model_file,
  chains = chains,
  iter = iterations,
  cores = nc,
  seed = seed,
  data = df_tpt$stan_dat
)
```

```{r tpt-fit}
# get estimates/predictions
pred_tpt <- get_estimates(df_tpt$dat, df_tpt$stan_dat, m_tpt)

# plot model fit
ggplot(mapping = aes(x = year_quart)) +
  stat_lineribbon(
    data = pred_tpt %>% filter(year_quart <= 2023),
    mapping = aes(y = pred),
    .width = c(.5, .95)
  ) +
  geom_line(
    data = pred_tpt %>%
      group_by(record_id, year_quart) %>%
      slice(1) %>%
      filter(year_quart <= 2023),
    mapping = aes(y = y),
    color = "red"
  ) +
  facet_wrap(~record_id, scales = "free_y") +
  scale_fill_brewer()

ggsave("results/tpt-by-site.png", width = 16, height = 12)
```

```{r tpt-plot}
pred_tpt_df <- bind_rows(
  pred_tpt %>%
    mutate(subgroup = "Global"),
  pred_tpt %>%
    mutate(subgroup = site_region)
)

subgroup_lab <- c(
  "Global" = "Global",
  "Africa" = "Africa",
  "Asia-Pacific" = "Asia Pacific"
)

est_cases_tpt <- pred_tpt_df %>%
  group_by(.draw, year_quart, subgroup) %>%
  summarize(pred = sum(pred)) %>%
  ungroup() %>%
  group_by(year_quart, subgroup) %>%
  median_qi() %>%
  ungroup() %>%
  filter(year_quart <= 2023) %>%
  mutate(
    subgroup = dplyr::recode(subgroup, !!!subgroup_lab),
    subgroup = factor(subgroup, levels = subgroup_lab)
  )

tpt_pl <- ggplot(
  data = est_cases_tpt,
  mapping = aes(x = year_quart) #  - .25
) +
  geom_line(aes(y = pred)) +
  geom_ribbon(
    aes(
      ymin = .lower, ymax = .upper
    ),
    alpha = .25
  ) +
  facet_wrap(
    ~subgroup,
    dir = "h",
    ncol = 3,
    scales = "free"
  ) +
  scale_color_manual(values = c("darkred", "black")) +
  scale_fill_manual(values = c("darkred", "black")) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0)),
    limits = c(2018.25, 2023.25),
    breaks = seq(2018.25, 2023.25, 1),
    labels = function(x) x - 0.25
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    labels = scales::comma
  ) +
  labs(
    fill = "CrI",
    y = "Number of TPT initiations"
  ) +
  theme_custom() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    panel.spacing = unit(.25, "cm"),
    strip.text = element_text(size = 8, face = 2, margin = margin(b = 5.5)),
    plot.margin = margin(r = 10),
  )

save_plot(
  tpt_pl,
  pdf_file = "results/tpt-imputed.png",
  w = 16, h = 5
)
```